databases:
  - name: rails_mister_cocktail
    databaseName: rails_mister_cocktail_production
    user: rails_mister_cocktail

services:
  - type: web
    name: mister-cocktail
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mister-cocktail
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
